services:
   palworld:
      image: thijsvanloef/palworld-server-docker:user
      build:
         dockerfile: Dockerfile
      # restart: unless-stopped
      container_name: palworld-server-user
      # Works if you set to 1000:1000 (default of steam user)
      user: 5000:5000
      ports:
        - 8212:8211/udp
        #- 27015:27015/udp # Required if you want your server to show up in the community servers tab 
      environment:
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="worldofpals" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="adminPasswordHere"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="World of Pals"
         - SERVER_DESCRIPTION=""
      volumes:
         - ./palworld:/palworld/
